### PR TITLE
created PR for #25

### PR DESCRIPTION
**Pull request by S3-26**
For issue #33
Problem statement 25

### CODE REVIEW

**Comment by gauri-bitsandbytes** [comment]
Please mention issue number in PR description. (#...)

**Comment by S3-26** [comment]
I have updated it. Please check it once

**Comment by gauri-bitsandbytes** [comment]
Please mention correct issue number #33 so that it gets linked when you mention

**Comment by gauri-bitsandbytes** [comment]
Please mention correct issue number as #issue_number.

**Comment by S3-26** [comment]
Sorry for the inconvenience.
Now please check it.

**Comment by srushti1006** [comment]
@S3-26 you have to mention the issue number in the comment i.e "Created solution for #issue " If you don't do this we will decline your PR.

**Pull request merged**
